name: Deploy

on:
  push:
    branches: [main, master]
  workflow_dispatch:

jobs:
  deploy:
    uses: mark-baumann/infrastruktur-deployment/.github/workflows/build-deploy.yml@master
    with:
        service_name: schach
        port: "8520"
        app_file: app.py
        healthcheck_type: http
    secrets: inherit
